routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('monitoring-reports/destroy', 'MonitoringReportController@massDestroy')->name('monitoring-reports.massDestroy');

    Route::resource('monitoring-reports', 'MonitoringReportController');

    Route::put('evaluation/update-evaluation/{monitoringReport}', 'MonitoringReportController@updateSingleEvaluation')->name('monitoring-reports.updateSingleEvaluation');

    Route::put('report-comment/{monitoringReport}', 'MonitoringReportController@comment')->name('monitoring-reports.comment');

    Route::delete('criteria/destroy', 'CriteriaController@massDestroy')->name('criteria.massDestroy');

    Route::resource('criteria', 'CriteriaController');

    Route::delete('evaluations/destroy', 'EvaluationController@massDestroy')->name('evaluations.massDestroy');

    Route::resource('evaluations', 'EvaluationController');

    Route::delete('tools/destroy', 'ToolController@massDestroy')->name('tools.massDestroy');

    Route::resource('tools', 'ToolController');
});

resources/views/partials/datatablesActions.blade.php
@can($viewGate, $row)
    <a class="btn btn-sm btn-primary" href="{{ route('admin.' . $crudRoutePart . '.show', $row->id) }}" title="Žiūrėti">
        <i class="far fa-eye"></i>
    </a>
@endcan
@can($editGate, $row)
    <a class="btn btn-sm btn-info" href="{{ route('admin.' . $crudRoutePart . '.edit', $row->id) }}" title="Taisyti">
        <i class="far fa-edit"></i>
    </a>
@endcan
@can($deleteGate, $row)
    <form action="{{ route('admin.' . $crudRoutePart . '.destroy', $row->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <button type="submit" class="btn btn-sm btn-danger" title="Trinti"><i class="far fa-trash-alt"></i></button>
    </form>
@endcan

resources/views/partials/menu.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="min-height: 917px;">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <span class="brand-text font-weight-light">Kompetencijos vertinimas</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{ route("admin.home") }}" class="nav-link">
                        <p>
                            <i class="fas fa-fw fa-tachometer-alt">

                            </i>
                            <span>Meniu</span>
                        </p>
                    </a>
                </li>
                @can('user_management_access')
                    <li class="nav-item has-treeview {{ request()->is('admin/permissions*') ? 'menu-open' : '' }} {{ request()->is('admin/roles*') ? 'menu-open' : '' }} {{ request()->is('admin/users*') ? 'menu-open' : '' }}">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            <i class="fa-fw fas fa-users">

                            </i>
                            <p>
                                <span>{{ trans('cruds.userManagement.title') }}</span>
                                <i class="right fa fa-fw fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            @can('permission_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.permissions.index") }}" class="nav-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                        <i class="fa-fw fas fa-unlock-alt">

                                        </i>
                                        <p>
                                            <span>{{ trans('cruds.permission.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('role_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.roles.index") }}" class="nav-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                        <i class="fa-fw fas fa-briefcase">

                                        </i>
                                        <p>
                                            <span>{{ trans('cruds.role.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('user_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.users.index") }}" class="nav-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                        <i class="fa-fw fas fa-user">

                                        </i>
                                        <p>
                                            <span>{{ trans('cruds.user.title') }}</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                        </ul>
                    </li>
                @endcan
                @can('competency_access')
                    <li class="nav-item has-treeview {{ request()->is('admin/monitoring-reports*') ? 'menu-open' : '' }} {{ request()->is('admin/points*') ? 'menu-open' : '' }} {{ request()->is('admin/criteria*') ? 'menu-open' : '' }} {{ request()->is('admin/evaluations*') ? 'menu-open' : '' }}">
                        <a class="nav-link nav-dropdown-toggle" href="#">
                            <i class="fa-fw fas fa-star-half-alt">

                            </i>
                            <p>
                                <span>Vertinimas</span>
                                <i class="right fa fa-fw fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            @can('monitoring_report_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.monitoring-reports.index") }}" class="nav-link {{ request()->is('admin/monitoring-reports') || request()->is('admin/monitoring-reports/*') ? 'active' : '' }}">
                                        <i class="fa-fw fas fa-star-half-alt">

                                        </i>
                                        <p>
                                            <span>Stebėjimo ataskaitos</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                            @can('criterion_access')
                                <li class="nav-item">
                                    <a href="{{ route("admin.criteria.index") }}" class="nav-link {{ request()->is('admin/criteria') || request()->is('admin/criteria/*') ? 'active' : '' }}">
                                        <i class="fa-fw fas fa-file-alt">

                                        </i>
                                        <p>
                                            <span>Darbo aspektai</span>
                                        </p>
                                    </a>
                                </li>
                            @endcan
                        </ul>
                    </li>
                @endcan
                @can('tool_access')
                    <li class="nav-item">
                        <a href="{{ route("admin.tools.index") }}" class="nav-link {{ request()->is('admin/tools') || request()->is('admin/tools/*') ? 'active' : '' }}">
                            <i class="fa-fw fas fa-cogs">

                            </i>
                            <p>
                                <span>Kas nors dar...</span>
                            </p>
                        </a>
                    </li>
                @endcan
                <li class="nav-item">
                    <a href="#" class="nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                        <p class="text-info">
                            <i class="fas fa-fw fa-sign-out-alt">

                            </i>
                            <span>Atsijungti</span>
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>