routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('monitoring-reports/destroy', 'MonitoringReportController@massDestroy')->name('monitoring-reports.massDestroy');

    Route::resource('monitoring-reports', 'MonitoringReportController');

    Route::put('evaluation/update-evaluation/{monitoringReport}', 'MonitoringReportController@updateSingleEvaluation')->name('monitoring-reports.updateSingleEvaluation');

    Route::put('report-comment/{monitoringReport}', 'MonitoringReportController@comment')->name('monitoring-reports.comment');

    Route::delete('criteria/destroy', 'CriteriaController@massDestroy')->name('criteria.massDestroy');

    Route::resource('criteria', 'CriteriaController');

    Route::delete('evaluations/destroy', 'EvaluationController@massDestroy')->name('evaluations.massDestroy');

    Route::resource('evaluations', 'EvaluationController');

    Route::delete('tools/destroy', 'ToolController@massDestroy')->name('tools.massDestroy');

    Route::resource('tools', 'ToolController');
});

app/Http/Controllers/Admin/CriteriaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Criterion;
use App\Competency;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCriterionRequest;
use App\Http\Requests\StoreCriterionRequest;
use App\Http\Requests\UpdateCriterionRequest;

class CriteriaController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('is_admin'), 403);

        $criteria = Criterion::all();

        return view('admin.criteria.index', compact('criteria'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('is_admin'), 403);

        $competencies = Competency::all()->pluck('title', 'id');
        return view('admin.criteria.create', compact('competencies'));
    }

    public function store(StoreCriterionRequest $request)
    {
        abort_unless(\Gate::allows('is_admin'), 403);
        $criterion = Criterion::create($request->all());

        return redirect()->route('admin.criteria.index');
    }

    public function edit(Criterion $criterion)
    {
        abort_unless(\Gate::allows('criterion_edit'), 403);

        $competencies = Competency::all()->pluck('title', 'id');
        return view('admin.criteria.edit', compact('criterion', 'competencies'));
    }

    public function update(StoreCriterionRequest $request, Criterion $criterion)
    {
        abort_unless(\Gate::allows('criterion_edit'), 403);

        $criterion->update($request->all());

        return redirect()->route('admin.criteria.index');
    }

    public function show(Criterion $criterion)
    {
        abort_unless(\Gate::allows('criterion_show'), 403);

        return view('admin.criteria.show', compact('criterion'));
    }

    public function destroy(Criterion $criterion)
    {
        abort_unless(\Gate::allows('criterion_delete'), 403);

        $criterion->delete();

        return back();
    }

    public function massDestroy(MassDestroyCriterionRequest $request)
    {
        Criterion::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

resources/views/admin/criteria/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Sukurti naują darbo aspektą
    </div>

    <div class="card-body">
        <form action="{{ route("admin.criteria.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('cruds.criterion.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($criterion) ? $criterion->title : '') }}" required>
                @if($errors->has('title'))
                    <p class="help-block">
                        {{ $errors->first('title') }}
                    </p>
                @endif

            </div>
            <div class="form-group {{ $errors->has('competency_id') ? 'has-error' : '' }}">
                <label for="competency_id">Kompetencija*</label>
                <select name="competency_id" id="competency_id" class="form-control select2" required>
                    @foreach($competencies as $id => $competency)
                        <option value="{{ $id }}" {{ old('competency_id') == $id ? 'selected' : ''}} > {{ $competency }} </option>
                    @endforeach
                </select>
                @if($errors->has('competency_id'))
                    <p class="help-block">
                        {{ $errors->first('competency_id') }}
                    </p>
                @endif
            </div>

            <div>
                <input class="btn btn-danger" type="submit" value="Išsaugoti">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/criteria/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.criterion.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.criteria.update", [$criterion->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('cruds.criterion.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($criterion) ? $criterion->title : '') }}" required>
                @if($errors->has('title'))
                    <p class="help-block">
                        {{ $errors->first('title') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.criterion.fields.title_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('competency_id') ? 'has-error' : '' }}">
                <label for="competency_id">{{ trans('cruds.criterion.fields.category') }}*</label>
                <select name="competency_id" id="competency_id" class="form-control select2" required>
                    @foreach($competencies as $id => $competency)
                        <option value="{{ $id }}" {{ old('competency_id', $criterion->competency_id) == $id ? 'selected' : '' }} > {{ $competency }} </option>
                    @endforeach
                </select>
                @if($errors->has('competency_id'))
                    <p class="help-block">
                        {{ $errors->first('competency_id') }}
                    </p>
                @endif
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="Išsaugoti">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/criteria/index.blade.php
@extends('layouts.admin')
@section('content')
@can('criterion_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.criteria.create") }}">
                Naujas darbo aspektas
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        Darbo aspektų sąrašas
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            Pavadinimas
                        </th>
                        <th>
                            Kompetencija
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($criteria as $key => $criterion)
                        <tr data-entry-id="{{ $criterion->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $criterion->title ?? '' }}
                            </td>
                            <td>
                                {{ $criterion->competency->title ?? '' }}
                            </td>
                            <td>
                                @can('is_admin')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.criteria.show', $criterion->id) }}">
                                        Rodyti
                                    </a>
                                @endcan
                                @can('is_admin')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.criteria.edit', $criterion->id) }}">
                                        Taisyti
                                    </a>
                                @endcan
                                @can('is_admin')
                                    <form action="{{ route('admin.criteria.destroy', $criterion->id) }}" method="POST" onsubmit="return confirm('Ar tikrai trinti?');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="Trinti">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.criteria.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('criterion_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection

resources/views/admin/criteria/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        Darbo aspektas
    </div>

    <div class="card-body">
        <div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            Pavadinimas
                        </th>
                        <td>
                            {{ $criterion->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Kompetencija
                        </th>
                        <td>
                            {{ $criterion->competency->title }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                Atgal į sąrašą
            </a>
        </div>
    </div>
</div>
@endsection