routes/web.php
<?php

Route::redirect('/', '/login');

Route::redirect('/home', '/admin');

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('monitoring-reports/destroy', 'MonitoringReportController@massDestroy')->name('monitoring-reports.massDestroy');

    Route::resource('monitoring-reports', 'MonitoringReportController');

    Route::put('evaluation/update-evaluation/{monitoringReport}', 'MonitoringReportController@updateSingleEvaluation')->name('monitoring-reports.updateSingleEvaluation');

    Route::put('report-comment/{monitoringReport}', 'MonitoringReportController@comment')->name('monitoring-reports.comment');

    Route::delete('criteria/destroy', 'CriteriaController@massDestroy')->name('criteria.massDestroy');

    Route::resource('criteria', 'CriteriaController');

    Route::delete('evaluations/destroy', 'EvaluationController@massDestroy')->name('evaluations.massDestroy');

    Route::resource('evaluations', 'EvaluationController');

    Route::delete('tools/destroy', 'ToolController@massDestroy')->name('tools.massDestroy');

    Route::resource('tools', 'ToolController');
});

app/Tool.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Tool extends Model
{
    use SoftDeletes;

    public $table = 'tools';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'note',
        'title',
        'model',
        'branch_id',
        'condition',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    public function branch()
    {
        return $this->belongsTo('App\Branch');
    }
}

app/Http/Controllers/Admin/ToolController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyToolRequest;
use App\Http\Requests\StoreToolRequest;
use App\Http\Requests\UpdateToolRequest;
use App\Tool;

class ToolController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('tool_access'), 403);

        $tools = Tool::all();

        return view('admin.tools.index', compact('tools'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('tool_create'), 403);

        return view('admin.tools.create');
    }

    public function store(StoreToolRequest $request)
    {
        abort_unless(\Gate::allows('tool_create'), 403);

        $tool = Tool::create($request->all());

        return redirect()->route('admin.tools.index');
    }

    public function edit(Tool $tool)
    {
        abort_unless(\Gate::allows('tool_edit'), 403);

        return view('admin.tools.edit', compact('tool'));
    }

    public function update(UpdateToolRequest $request, Tool $tool)
    {
        abort_unless(\Gate::allows('tool_edit'), 403);

        $tool->update($request->all());

        return redirect()->route('admin.tools.index');
    }

    public function show(Tool $tool)
    {
        abort_unless(\Gate::allows('tool_show'), 403);

        return view('admin.tools.show', compact('tool'));
    }

    public function destroy(Tool $tool)
    {
        abort_unless(\Gate::allows('tool_delete'), 403);

        $tool->delete();

        return back();
    }

    public function massDestroy(MassDestroyToolRequest $request)
    {
        Tool::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

resources/views/admin/tools/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.tool.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.tools.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('cruds.tool.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($tool) ? $tool->title : '') }}" required>
                @if($errors->has('title'))
                    <p class="help-block">
                        {{ $errors->first('title') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.title_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('model') ? 'has-error' : '' }}">
                <label for="model">{{ trans('cruds.tool.fields.model') }}</label>
                <input type="text" id="model" name="model" class="form-control" value="{{ old('model', isset($tool) ? $tool->model : '') }}">
                @if($errors->has('model'))
                    <p class="help-block">
                        {{ $errors->first('model') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.model_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('condition') ? 'has-error' : '' }}">
                <label for="condition">{{ trans('cruds.tool.fields.condition') }}*</label>
                <input type="text" id="condition" name="condition" class="form-control" value="{{ old('condition', isset($tool) ? $tool->condition : '') }}" required>
                @if($errors->has('condition'))
                    <p class="help-block">
                        {{ $errors->first('condition') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.condition_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('note') ? 'has-error' : '' }}">
                <label for="note">{{ trans('cruds.tool.fields.note') }}</label>
                <textarea id="note" name="note" class="form-control ">{{ old('note', isset($tool) ? $tool->note : '') }}</textarea>
                @if($errors->has('note'))
                    <p class="help-block">
                        {{ $errors->first('note') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.note_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('branch') ? 'has-error' : '' }}">
                <label for="branch">{{ trans('cruds.tool.fields.branch') }}*</label>
                <input type="text" id="branch" name="branch" class="form-control" value="{{ old('branch', isset($tool) ? $tool->branch : '') }}" required>
                @if($errors->has('branch'))
                    <p class="help-block">
                        {{ $errors->first('branch') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.branch_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tools/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.tool.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.tools.update", [$tool->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                <label for="title">{{ trans('cruds.tool.fields.title') }}*</label>
                <input type="text" id="title" name="title" class="form-control" value="{{ old('title', isset($tool) ? $tool->title : '') }}" required>
                @if($errors->has('title'))
                    <p class="help-block">
                        {{ $errors->first('title') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.title_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('model') ? 'has-error' : '' }}">
                <label for="model">{{ trans('cruds.tool.fields.model') }}</label>
                <input type="text" id="model" name="model" class="form-control" value="{{ old('model', isset($tool) ? $tool->model : '') }}">
                @if($errors->has('model'))
                    <p class="help-block">
                        {{ $errors->first('model') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.model_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('condition') ? 'has-error' : '' }}">
                <label for="condition">{{ trans('cruds.tool.fields.condition') }}*</label>
                <input type="text" id="condition" name="condition" class="form-control" value="{{ old('condition', isset($tool) ? $tool->condition : '') }}" required>
                @if($errors->has('condition'))
                    <p class="help-block">
                        {{ $errors->first('condition') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.condition_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('note') ? 'has-error' : '' }}">
                <label for="note">{{ trans('cruds.tool.fields.note') }}</label>
                <textarea id="note" name="note" class="form-control ">{{ old('note', isset($tool) ? $tool->note : '') }}</textarea>
                @if($errors->has('note'))
                    <p class="help-block">
                        {{ $errors->first('note') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.note_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('branch') ? 'has-error' : '' }}">
                <label for="branch">{{ trans('cruds.tool.fields.branch') }}*</label>
                <input type="text" id="branch" name="branch" class="form-control" value="{{ old('branch', isset($tool) ? $tool->branch : '') }}" required>
                @if($errors->has('branch'))
                    <p class="help-block">
                        {{ $errors->first('branch') }}
                    </p>
                @endif
                <p class="helper-block">
                    {{ trans('cruds.tool.fields.branch_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>
@endsection

resources/views/admin/tools/index.blade.php
@extends('layouts.admin')
@section('content')
@can('tool_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.tools.create") }}">
                {{ trans('global.add') }} {{ trans('cruds.tool.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.tool.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.tool.fields.title') }}
                        </th>
                        <th>
                            {{ trans('cruds.tool.fields.model') }}
                        </th>
                        <th>
                            {{ trans('cruds.tool.fields.condition') }}
                        </th>
                        <th>
                            {{ trans('cruds.tool.fields.note') }}
                        </th>
                        <th>
                            {{ trans('cruds.tool.fields.branch') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($tools as $key => $tool)
                        <tr data-entry-id="{{ $tool->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $tool->title ?? '' }}
                            </td>
                            <td>
                                {{ $tool->model ?? '' }}
                            </td>
                            <td>
                                {{ $tool->condition ?? '' }}
                            </td>
                            <td>
                                {{ $tool->note ?? '' }}
                            </td>
                            <td>
                                {{ $tool->branch->title ?? '' }}
                            </td>
                            <td>
                                @can('tool_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.tools.show', $tool->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('tool_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.tools.edit', $tool->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('tool_delete')
                                    <form action="{{ route('admin.tools.destroy', $tool->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.tools.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('tool_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection

resources/views/admin/tools/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.tool.title') }}
    </div>

    <div class="card-body">
        <div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.tool.fields.title') }}
                        </th>
                        <td>
                            {{ $tool->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tool.fields.model') }}
                        </th>
                        <td>
                            {{ $tool->model }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tool.fields.condition') }}
                        </th>
                        <td>
                            {{ $tool->condition }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tool.fields.note') }}
                        </th>
                        <td>
                            {!! $tool->note !!}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.tool.fields.branch') }}
                        </th>
                        <td>
                            {{ $tool->branch }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <a style="margin-top:20px;" class="btn btn-default" href="{{ url()->previous() }}">
                {{ trans('global.back_to_list') }}
            </a>
        </div>
    </div>
</div>
@endsection